kotlin.code.style=official
kotest.framework.classpath.scanning.autoscan.disable=true
org.gradle.jvmargs=-Xmx1g
# Publishing configuration
version=0.1.0
group=dev.ktool
inception.year=2025
scm.org.url=https://github.com/ktool-dev
scm.repo.path=github.com/ktool-dev/ktembed
developer.id=aaronfreeman
developer.name=Aaron Freeman
developer.email=aaron@ktool.dev
license.name="MIT License"
license.url="https://mit-license.org/"
